/* Writes sdk/generated.ts from the IDL that `anchor build` just produced: the
 * program address and every instruction, account and event discriminator.
 * The SDK encodes instructions by hand from these, so it carries no Anchor
 * client into the browser. Run after every program change:  npm run gen */

import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const IDL = path.resolve(ROOT, "target/idl/earnout.json");
const OUT = path.resolve(ROOT, "sdk/generated.ts");

if (!fs.existsSync(IDL)) {
  console.error("No target/idl/earnout.json. Run:  anchor build");
  process.exit(1);
}

type Named = { name: string; discriminator: number[] };
const idl = JSON.parse(fs.readFileSync(IDL, "utf8")) as {
  address: string;
  instructions: Named[];
  accounts?: Named[];
  events?: Named[];
};

const table = (items: Named[] = []) =>
  items.map((i) => `  ${i.name}: new Uint8Array([${i.discriminator.join(", ")}]),`).join("\n");

const src = `// Generated by scripts/gen-sdk.ts from target/idl/earnout.json. Do not edit.
import { address } from "@solana/kit";

export const PROGRAM_ADDRESS = address("${idl.address}");

export const IX = {
${table(idl.instructions)}
} as const;

export const ACCOUNT = {
${table(idl.accounts)}
} as const;

export const EVENT = {
${table(idl.events)}
} as const;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, src);
console.log(`Wrote ${path.relative(ROOT, OUT)} for ${idl.address}`);
