import type { Metadata } from "next";
import { SiteHeader } from "@/components/dashboard/Pieces";
import { SiteFooter } from "@/components/SiteShell";

export const metadata: Metadata = {
  title: "Brand",
  description: "The Earnout logo, in every form, as SVG and PNG, ready to download.",
};

/* The files are generated by scripts/brand.ts; this page only shows them,
 * each on the background it is meant for, with its SVG and PNGs beside it. */

type Item = { svg: string; label: string; bg: "paper" | "ink" | "checker"; wide?: boolean; pngs: string[] };

const ASSETS: { title: string; note: string; items: Item[] }[] = [
  {
    title: "Logo",
    note: "The mark and the wordmark together. Use this wherever there is room.",
    items: [
      { svg: "logo.svg", label: "Ink, for light backgrounds", bg: "paper", wide: true, pngs: ["logo-2048.png"] },
      { svg: "logo-inverse.svg", label: "Paper, for dark backgrounds", bg: "ink", wide: true, pngs: ["logo-inverse-2048.png"] },
    ],
  },
  {
    title: "Mark",
    note: "A receipt slip with a tick: a record that something was paid. The tick is cut out, so the background shows through.",
    items: [
      { svg: "mark.svg", label: "Ink", bg: "paper", pngs: ["mark-512.png", "mark-1024.png"] },
      { svg: "mark-inverse.svg", label: "Paper", bg: "ink", pngs: ["mark-inverse-512.png", "mark-inverse-1024.png"] },
      { svg: "mark-paid.svg", label: "Paid green, the one accent", bg: "paper", pngs: ["mark-paid-512.png", "mark-paid-1024.png"] },
    ],
  },
  {
    title: "Wordmark",
    note: "Geist SemiBold, converted to paths, so the file needs no font.",
    items: [
      { svg: "wordmark.svg", label: "Ink", bg: "paper", wide: true, pngs: ["wordmark-2048.png"] },
      { svg: "wordmark-inverse.svg", label: "Paper", bg: "ink", wide: true, pngs: ["wordmark-inverse-2048.png"] },
    ],
  },
  {
    title: "App icon",
    note: "Full bleed, no rounded corners: for X, Colosseum, app stores and anywhere else that masks icons itself. Whatever shape they cut, there is always ink underneath, and the mark sits inside the circle.",
    items: [
      { svg: "icon.svg", label: "App icon, dark (use this one)", bg: "checker", pngs: ["icon-512.png", "icon-1024.png"] },
      { svg: "icon-light.svg", label: "App icon, light", bg: "checker", pngs: ["icon-light-512.png", "icon-light-1024.png"] },
    ],
  },
  {
    title: "Avatars and banners",
    note: "Rounded tiles for places that do not mask icons themselves, and 1500 by 500 banners for headers.",
    items: [
      { svg: "avatar.svg", label: "Avatar", bg: "checker", pngs: ["avatar-1024.png"] },
      { svg: "avatar-dark.svg", label: "Avatar, dark", bg: "checker", pngs: ["avatar-dark-1024.png"] },
      { svg: "banner.svg", label: "Banner", bg: "checker", wide: true, pngs: ["banner-1500x500.png"] },
      { svg: "banner-dark.svg", label: "Banner, dark", bg: "checker", wide: true, pngs: ["banner-dark-1500x500.png"] },
    ],
  },
];

const sizeOf = (png: string) => png.replace(/^.*?-(\d+(?:x\d+)?)\.png$/, "$1");

function DownloadPill({ file, label }: { file: string; label: string }) {
  return (
    <a
      href={`/brand/${file}`}
      download
      className="rounded-full border border-line px-3 py-1 font-mono text-[11px] transition-colors hover:border-ink"
    >
      {label}
    </a>
  );
}

export default function BrandPage() {
  return (
    <>
      <SiteHeader />
      <main id="content" className="mx-auto max-w-6xl px-4 py-14 sm:px-6">
        <p className="font-mono text-xs tracking-[0.2em] text-muted uppercase">Brand</p>
        <h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">The Earnout logo</h1>
        <p className="mt-4 max-w-2xl text-lg leading-8 text-muted">
          Paper and ink, like a printed receipt. Green is used for one thing only: money that was paid. Every asset comes
          as a vector and as PNG, on a transparent background unless it is an avatar or banner.
        </p>
        <div className="mt-6 flex flex-wrap gap-3">
          <a href="/brand/earnout-brand.zip" download className="rounded-full bg-ink px-5 py-2.5 font-medium text-paper hover:opacity-90">
            Download the whole kit (zip)
          </a>
          <a href="https://github.com/Cryptonomist/earnout/tree/main/public/brand" className="rounded-full border border-line px-5 py-2.5 font-medium hover:border-ink">
            Browse on GitHub
          </a>
        </div>

        {ASSETS.map((group) => (
          <section key={group.title} className="mt-14">
            <h2 className="text-2xl font-semibold tracking-tight">{group.title}</h2>
            <p className="mt-2 max-w-2xl leading-7 text-muted">{group.note}</p>
            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {group.items.map((item) => (
                <figure key={item.svg} className={`overflow-hidden rounded-2xl border border-line ${item.wide ? "sm:col-span-2 lg:col-span-3" : ""}`}>
                  <div
                    className={`flex items-center justify-center p-10 ${
                      item.bg === "paper" ? "bg-[#f4f2eb]" : item.bg === "ink" ? "bg-[#16150f]" : "checker"
                    }`}
                  >
                    {/* Plain img: these are the shipped files, shown as they are. */}
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={`/brand/${item.svg}`} alt={item.label} className={item.wide ? "h-16 w-auto max-w-full" : "size-24"} />
                  </div>
                  <figcaption className="flex flex-wrap items-center justify-between gap-3 border-t border-line px-4 py-3 text-sm">
                    <span>{item.label}</span>
                    <span className="flex flex-wrap gap-2">
                      <DownloadPill file={item.svg} label="SVG" />
                      {item.pngs.map((p) => (
                        <DownloadPill key={p} file={p} label={`PNG ${sizeOf(p)}`} />
                      ))}
                    </span>
                  </figcaption>
                </figure>
              ))}
            </div>
          </section>
        ))}

        <section className="mt-14 max-w-2xl leading-7 text-muted">
          <h2 className="text-2xl font-semibold tracking-tight text-ink">Using it</h2>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>Keep clear space around the logo of at least the mark&apos;s own width.</li>
            <li>The mark alone works down to 16 pixels; the logo needs about 100 pixels of width.</li>
            <li>Ink on light, paper on dark. Do not recolour the wordmark; green is for the mark only, and only where &quot;paid&quot; is the message.</li>
            <li>Do not stretch, rotate, outline or add effects.</li>
            <li>Need another size? The SVGs scale to anything, and PNGs are exported from them.</li>
          </ul>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
