import type { Metadata } from "next";
import { SiteHeader } from "@/components/dashboard/Pieces";

export const metadata: Metadata = {
  title: "Brand",
  description: "The Earnout logo, in every form, ready to download.",
};

/* The files are generated by scripts/brand.ts; this page only shows them.
 * Each one is drawn on the background it is meant for. */

const ASSETS: { title: string; note: string; items: { file: string; label: string; bg: "paper" | "ink" | "checker"; wide?: boolean }[] }[] = [
  {
    title: "Logo",
    note: "The mark and the wordmark together. Use this wherever there is room.",
    items: [
      { file: "logo.svg", label: "Ink, for light backgrounds", bg: "paper", wide: true },
      { file: "logo-inverse.svg", label: "Paper, for dark backgrounds", bg: "ink", wide: true },
    ],
  },
  {
    title: "Mark",
    note: "A receipt slip with a tick: a record that something was paid. The tick is cut out, so the background shows through.",
    items: [
      { file: "mark.svg", label: "Ink", bg: "paper" },
      { file: "mark-inverse.svg", label: "Paper", bg: "ink" },
      { file: "mark-paid.svg", label: "Paid green, the one accent", bg: "paper" },
    ],
  },
  {
    title: "Wordmark",
    note: "Geist SemiBold, converted to paths, so the file needs no font.",
    items: [
      { file: "wordmark.svg", label: "Ink", bg: "paper", wide: true },
      { file: "wordmark-inverse.svg", label: "Paper", bg: "ink", wide: true },
    ],
  },
  {
    title: "Avatars and banners",
    note: "Square tiles for profile pictures, 1500 by 500 banners for headers.",
    items: [
      { file: "avatar.svg", label: "Avatar (avatar-1024.png)", bg: "checker" },
      { file: "avatar-dark.svg", label: "Avatar, dark (avatar-dark-1024.png)", bg: "checker" },
      { file: "banner.svg", label: "Banner (banner-1500x500.png)", bg: "checker", wide: true },
      { file: "banner-dark.svg", label: "Banner, dark (banner-dark-1500x500.png)", bg: "checker", wide: true },
    ],
  },
];

const PNGS = [
  "mark-512.png",
  "mark-inverse-512.png",
  "mark-paid-512.png",
  "logo-2048.png",
  "logo-inverse-2048.png",
  "avatar-1024.png",
  "avatar-dark-1024.png",
  "banner-1500x500.png",
  "banner-dark-1500x500.png",
];

export default function BrandPage() {
  return (
    <>
      <SiteHeader />
      <main className="mx-auto max-w-6xl px-4 py-14 sm:px-6">
        <p className="font-mono text-xs tracking-[0.2em] text-muted uppercase">Brand</p>
        <h1 className="mt-4 text-4xl font-semibold tracking-tight sm:text-5xl">The Earnout logo</h1>
        <p className="mt-4 max-w-2xl text-lg leading-8 text-muted">
          Paper and ink, like a printed receipt. Green is used for one thing only: money that was paid. Every file below
          is a vector; PNGs are at the bottom.
        </p>

        {ASSETS.map((group) => (
          <section key={group.title} className="mt-14">
            <h2 className="text-2xl font-semibold tracking-tight">{group.title}</h2>
            <p className="mt-2 max-w-2xl leading-7 text-muted">{group.note}</p>
            <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {group.items.map((item) => (
                <figure key={item.file} className={`overflow-hidden rounded-2xl border border-line ${item.wide ? "sm:col-span-2 lg:col-span-3" : ""}`}>
                  <div
                    className={`flex items-center justify-center p-10 ${
                      item.bg === "paper" ? "bg-[#f4f2eb]" : item.bg === "ink" ? "bg-[#16150f]" : "checker"
                    }`}
                  >
                    {/* Plain img: these are the shipped files, shown as they are. */}
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={`/brand/${item.file}`} alt={item.label} className={item.wide ? "h-16 w-auto max-w-full" : "size-24"} />
                  </div>
                  <figcaption className="flex items-center justify-between gap-4 border-t border-line px-4 py-3 text-sm">
                    <span>{item.label}</span>
                    <a href={`/brand/${item.file}`} download className="font-mono text-xs underline decoration-line underline-offset-2 hover:decoration-ink">
                      {item.file}
                    </a>
                  </figcaption>
                </figure>
              ))}
            </div>
          </section>
        ))}

        <section className="mt-14">
          <h2 className="text-2xl font-semibold tracking-tight">PNG exports</h2>
          <ul className="mt-4 flex flex-wrap gap-3">
            {PNGS.map((f) => (
              <li key={f}>
                <a href={`/brand/${f}`} download className="rounded-full border border-line px-4 py-2 font-mono text-xs hover:border-ink">
                  {f}
                </a>
              </li>
            ))}
          </ul>
        </section>

        <section className="mt-14 max-w-2xl leading-7 text-muted">
          <h2 className="text-2xl font-semibold tracking-tight text-ink">Using it</h2>
          <ul className="mt-4 list-disc space-y-2 pl-5">
            <li>Keep clear space around the logo of at least the mark&apos;s own width.</li>
            <li>The mark alone works down to 16 pixels; the logo needs about 100 pixels of width.</li>
            <li>Ink on light, paper on dark. Do not recolour the wordmark; green is for the mark only, and only where &quot;paid&quot; is the message.</li>
            <li>Do not stretch, rotate, outline or add effects.</li>
          </ul>
        </section>
      </main>
    </>
  );
}
